### ISSUE TITLE
Created always return 1970-01-01T00:00:01Z

### ISSUE THREAD

**Issue by aronzillo** [WsdlToPhp/WsSecurity#1]
I am wanting to make a request without using passwordDigest, I am using the constructor like this:

`$soapHeader = WsSecurity::createWsSecuritySoapHeader($username, hash('sha256', $password), false, 1, 0, true, true)`

And soap header is: 

`<SOAP-ENV:Header>
    <wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" SOAP-ENV:mustunderstand="1">
      <wsse:UsernameToken>
        <wsse:Username>MyFantasticUser</wsse:Username>
        <wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText">1c8vsfg983......</wsse:Password>
        <wssu:Created xmlns:wssu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">1970-01-01T00:00:01Z</wssu:Created>
        <wsse:Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">mVgglxA=</wsse:Nonce>
      </wsse:UsernameToken>
    </wsse:Security>
  </SOAP-ENV:Header>`

The node <wssu:Created> always has this date:
`1970-01-01T00:00:01Z`

What am I doing wrong?

**Comment by mikaelcom** [comment]
If I were you I would have complained since a while ago as I see your issue only now 😢,

You passed 1 as the addCreated parameter which should instead be something as `time()` or anything that is a valid timestamp.:
> $addCreated: set it to the time you created this header using the PHP time function for example, otherwise pass 0

But you probably figured this out a long time ago now,
