### ISSUE TITLE
PackageGenerator

### ISSUE THREAD

**Issue by faithfulman18** [WsdlToPhp/WsSecurity#11]
Can this be used with the package generator project to include a WS security soap header within an outgoing package generated soap envelope?

**Comment by mikaelcom** [comment]
If you mean with the generated package in order to add a WsSecurity header to your Soap request, yes it can. I currently use it this way:
```php
/** @var WsdlToPhp\PackageBase\AbstractSoapClientBase $client **/
$client->getSoapClient()->__setSoapHeaders(WsSecurity::createWsSecuritySoapHeader(
    $username,
    $password
));

$client->theSoapMethod();
```

Is it what you seek?

It's currently not automatically used/implemented within the generated package, although it might one day, to be thought...

**Comment by faithfulman18** [comment]
Yes, I think so.  Thanks for that info.  I appreciate it.

I've imported both packages from packageGenerator and from this project into a Laravel 8 project.  And I'm getting a soap fault object returned, but it's not firing off in my try/catch statement.   Otherwise I'd be further in trying to implement this.  But from what I can tell it does seem to be adding this section into the soapheader part of the soap packet.

**Comment by mikaelcom** [comment]
Not sure to follow, feel free to share some code ;)

**Comment by faithfulman18** [comment]
So, this is a bit of a weird one, but the vendor requires you download the wsdl manually, so I have the wsdl and then a location pointing the URL.  

`   
    $options = array(
      \WsdlToPhp\PackageBase\AbstractSoapClientBase::WSDL_URL => 'C:\WSDL\THIS_WSDL.wsdl',
      \WsdlToPhp\PackageBase\AbstractSoapClientBase::WSDL_CLASSMAP => \THIS_WSDL\ClassMap::get(),
      \WsdlToPhp\PackageBase\AbstractSoapClientBase::WSDL_SOAP_VERSION => SOAP_1_1,
      \WsdlToPhp\PackageBase\AbstractSoapClientBase::WSDL_CACHE_WSDL => WSDL_CACHE_BOTH,
      \WsdlToPhp\PackageBase\AbstractSoapClientBase::WSDL_EXCEPTIONS => true,
      \WsdlToPhp\PackageBase\AbstractSoapClientBase::WSDL_TRACE => false,
      \WsdlToPhp\PackageBase\AbstractSoapClientBase::WSDL_LOCATION => $this->ActualUrl,
    );


    $get = new \THIS_WSDL\ServiceType\Get($options);


    $get->getSoapClient()->__setSoapHeaders(WsSecurity::createWsSecuritySoapHeader(
       $this->wsUser,
       $this->wsPass
    ));


   ...

   $dataObj = all the stuff into the object

   ...


   try {
      $get->DoThisMethod($dataObj);
      $resultsData = $get->getResult();
      if (is_soap_fault($resultsData)){
        echo "this soap error: ";
        print_r($get->getLastError());
        exit;
      }else{
        print_r($resultsData);
      }

    } catch (SoapFault $fault) {
      echo "Soap Fault Error: ";
      echo ($fault->getMessage());
      exit;
    } catch (Exception $e) {
      echo "Exception Error: ";
      print_r($e->getMessage());
      exit;      
    }
`

When the location isn't accessable it generates a soapfault but it isn't in the catch message so I see this:

```
this soap error: 
Array
(
  [THIS_WSDL\ServiceType\Get:DoThisMethod] => SoapFault Object
   (
     [message:protected] => Could not connect to host
     ...
     ...
     ...
```

So, even though it's a soap fault object, it's not "catching" in the try/catch on that.  Maybe because it's inside of an array?  Or maybe I've missed a step?

**Comment by mikaelcom** [comment]
try using:
```php
\WsdlToPhp\PackageBase\AbstractSoapClientBase::WSDL_TRACE => true
```

`The trace option enables tracing of request so faults can be backtraced. This defaults to false` :wink:

**Comment by faithfulman18** [comment]
By changing this it still doesn't trigger the catch statements when there is a soap fault.

It's really weird, but the Exception or the SoapFault is contained within an object coming back.

```
    try {
      $get->ThisMethod($dataObject);
      
      $resultsData = $get->getResult();

      if (is_soap_fault($resultsData)){
        echo "not hitting catch but is soap fault";
        echo gettype($resultsData);
        exit;
    } catch (SoapFault $fault) {
      echo "Soap Fault Error: ";
      echo ($fault->getMessage());
      exit;
    } catch (Exception $e) {
      echo "Exception Error: ";
      print_r($e->getMessage());
      exit;      
    }
```


The output shows as this:

```
 not hitting catch but is soap fault
Object
```

And when I print out the data in the object it is indeed a soap fault.  Not sure if you have any ideas?  I am using the package inside of Laravel.

**Comment by mikaelcom** [comment]
The SoapFault [is catched and stored within the ServiceType instance](https://github.com/WsdlToPhp/PackageEws365/blob/develop/src/ServiceType/EwsAdd.php#L70-L78), you don't get to catch the SoapFault...

You have to check if `false === $resultsData`, if so get the lastError for the called method, otherwise check that `$resultsData` is an instance or has the type it must have.

**Comment by faithfulman18** [comment]
Oh .... Okay.  I guess I'm just not remembering that it worked that way.  Thanks for the explanation.

**Comment by mikaelcom** [comment]
it is now detailed in the soon-to-be-released [MANIFEST](https://github.com/WsdlToPhp/PackageGenerator/blob/feature/issue-124/MANIFEST.md#service-classes)

**Comment by faithfulman18** [comment]
Thanks!
