### ISSUE TITLE
MTOM-XOP

### ISSUE THREAD

**Issue by RpfPHP** [WsdlToPhp/WsSecurity#13]
Good night mikaelcom,

You helped me with the header a little while ago and I appreciate it.
I am able to use all the services I needed but one.
I need to Upload a PDF file to a WSDL. I'm using WsSecutiry to create the Header and it's perfect. My problem is that to send the file I need it to be encoded in Base64. I'll send you the tag:

<xs: element minOccurs = "0" name = "file" type = "xs: base64Binary" />

The server returns to me that the attachment must be MTOM-XOP.
I saw on the internet that to send such an attachment, you must create a Header that looks like this:

Content-Type: multipart / related; type = "application / xop + xml";
boundary = "uuid: 0b2e9c8c-3b23-49bc-a925-b2b0435616af";

Do you know how I could create this Header? and how do I send this file? 

If you know any classes that can help me I will be grateful.

Complicated, the PHP documentation has nothing to do with it.
If you can help me again, I will be forever grateful. In fact, he recommended his friend to his class and he is using it perfectly.

**Comment by mikaelcom** [comment]
Hi,

This has nothing to do with WsSecurity then but with the GeneratorPackage or even the PackageBase project.

Indeed, attaching a file to a Soap request is not something I usually do, instead I more often had to handle attached file to a Soap response. Recently, sending the file was possible by sending the base64-encoded file content in the `file` element within the Soap request. Is this what you tried at first? Is it when the Soap Server responded with the "MTOM-XOP" attachment thing?

Please create this issue at the [PackageBase](https://github.com/WsdlToPhp/PackageBase/issues/new) project as it has to do with the possibility to send a special XML request. Link the new issue to this one and reply to my questions within this last one :wink:.

Thanks for your feedback by the way.

**Comment by RpfPHP** [comment]
Good morning mikaelcom,

Thank you then. I will pass my problem on to the PackageBase.
The API I am using is private and for this reason I will remove access data but I will pass my entire code there.
I am also in need of help in receiving files from an API and as you mentioned that you usually handle files received. I will ask for help. Hahaha.
Thank you for now.
