### ISSUE TITLE
How to not set nonce

### ISSUE THREAD

**Issue by rps-repo** [WsdlToPhp/WsSecurity#3]
Getting an error message:
Receiver Requirement for no nonce has not been met, Received token has a nonce specified

Is there any way to not set a nonce?

**Comment by mikaelcom** [comment]
There is now way currently to not set the nonce property. I keep this feature opened then.

**Comment by rps-repo** [comment]
I added a PR for this: https://github.com/WsdlToPhp/WsSecurity/pull/4

**Comment by mikaelcom** [comment]
Sorry! Weirdly, I was not watching my own project so I did no see any activity since.... the beginning!

I'll review it very soon.

**Comment by mikaelcom** [comment]
merged, tested and released!
